// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tiroksin.Infrastructure.Data;

#nullable disable

namespace Tiroksin.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128045335_AddParameterValueSeeds")]
    partial class AddParameterValueSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tiroksin.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.HasKey("Id")
                        .HasName("pk_achievements");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_achievements_code");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("PassScore")
                        .HasColumnType("integer")
                        .HasColumnName("pass_score");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_options");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_questions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_exam_category_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_exam_creator_id");

                    b.ToTable("exam", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("EmptyAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("empty_answers");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_answers");

                    b.HasKey("Id")
                        .HasName("pk_exam_attempt");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_attempt_exam_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_exam_attempt_user_id");

                    b.ToTable("exam_attempt", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_question");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_question_exam_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_exam_question_question_id");

                    b.ToTable("exam_question", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.GameAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<bool>("IsTimeout")
                        .HasColumnType("boolean")
                        .HasColumnName("is_timeout");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_option_id");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_game_answers");

                    b.HasIndex("GameSessionId")
                        .HasDatabaseName("ix_game_answers_game_session_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_game_answers_question_id");

                    b.HasIndex("SelectedOptionId")
                        .HasDatabaseName("ix_game_answers_selected_option_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_game_answers_user_id");

                    b.ToTable("game_answers", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_question_index");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_ids");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_game_sessions");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_game_sessions_room_id");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.GameSessionPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int?>("EliminatedAtQuestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("eliminated_at_question_index");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_eliminated");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_winner");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("TimeoutCount")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_answers");

                    b.HasKey("Id")
                        .HasName("pk_game_session_players");

                    b.HasIndex("GameSessionId")
                        .HasDatabaseName("ix_game_session_players_game_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_game_session_players_user_id");

                    b.ToTable("game_session_players", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ParameterDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("text")
                        .HasColumnName("validation_rules");

                    b.HasKey("Id")
                        .HasName("pk_parameter_definitions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_parameter_definitions_key");

                    b.ToTable("parameter_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1754),
                            DataType = "int",
                            DefaultValue = "60",
                            Description = "Her soru için veril en süre (saniye cinsinden)",
                            IsRequired = false,
                            Key = "QUESTION_TIME",
                            Name = "Soru Başına Süre",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1754),
                            ValidationRules = "{\"min\": 10, \"max\": 300}"
                        },
                        new
                        {
                            Id = new Guid("00000002-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1808),
                            DataType = "string",
                            Description = "Sorunun ait olduğu kategori (örn: Matematik, Fizik, Kimya)",
                            IsRequired = false,
                            Key = "CATEGORY",
                            Name = "Kategori",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1809),
                            ValidationRules = "{\"maxLength\": 100}"
                        },
                        new
                        {
                            Id = new Guid("00000003-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1813),
                            DataType = "string",
                            Description = "Sorunun ait olduğu konu (örn: Türev, Integral)",
                            IsRequired = false,
                            Key = "SUBJECT",
                            Name = "Konu",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1814),
                            ValidationRules = "{\"maxLength\": 200}"
                        },
                        new
                        {
                            Id = new Guid("00000004-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1817),
                            DataType = "string",
                            Description = "Sorunun ait olduğu alt konu",
                            IsRequired = false,
                            Key = "TOPIC",
                            Name = "Alt Konu",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1817),
                            ValidationRules = "{\"maxLength\": 200}"
                        },
                        new
                        {
                            Id = new Guid("00000005-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1833),
                            DataType = "string",
                            DefaultValue = "Orta",
                            Description = "Sorunun zorluk seviyesi (Kolay, Orta, Zor)",
                            IsRequired = false,
                            Key = "DIFFICULTY",
                            Name = "Zorluk Seviyesi",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1833),
                            ValidationRules = "{\"enum\": [\"Kolay\", \"Orta\", \"Zor\"]}"
                        },
                        new
                        {
                            Id = new Guid("00000006-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1837),
                            DataType = "json",
                            DefaultValue = "[]",
                            Description = "Soru etiketleri (JSON array)",
                            IsRequired = false,
                            Key = "TAGS",
                            Name = "Etiketler",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1837),
                            ValidationRules = "{\"type\": \"array\"}"
                        },
                        new
                        {
                            Id = new Guid("00000007-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1842),
                            DataType = "string",
                            Description = "Sorunun kaynağı (örn: TYT 2023, AYT 2022)",
                            IsRequired = false,
                            Key = "SOURCE",
                            Name = "Kaynak",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1842),
                            ValidationRules = "{\"maxLength\": 100}"
                        },
                        new
                        {
                            Id = new Guid("00000008-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1845),
                            DataType = "int",
                            Description = "Sorunun ait olduğu sınav yılı",
                            IsRequired = false,
                            Key = "YEAR",
                            Name = "Yıl",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1846),
                            ValidationRules = "{\"min\": 2000, \"max\": 2100}"
                        });
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ParameterValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("ParameterDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parameter_definition_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_parameter_values");

                    b.HasIndex("ParameterDefinitionId")
                        .HasDatabaseName("ix_parameter_values_parameter_definition_id");

                    b.HasIndex("EntityType", "EntityId", "ParameterDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_parameter_values_entity_type_entity_id_parameter_definition");

                    b.ToTable("parameter_values", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1993),
                            EntityId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000002-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1993),
                            Value = "Matematik"
                        },
                        new
                        {
                            Id = new Guid("10000001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1997),
                            EntityId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000003-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1997),
                            Value = "Temel Matematik"
                        },
                        new
                        {
                            Id = new Guid("10000001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2002),
                            EntityId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000004-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2002),
                            Value = "İşlem Önceliği"
                        },
                        new
                        {
                            Id = new Guid("10000002-0002-0002-0002-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2006),
                            EntityId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000002-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2006),
                            Value = "Matematik"
                        },
                        new
                        {
                            Id = new Guid("10000002-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2010),
                            EntityId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000003-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2010),
                            Value = "Cebir"
                        },
                        new
                        {
                            Id = new Guid("10000002-0002-0002-0002-000000000003"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2013),
                            EntityId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000004-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2013),
                            Value = "İkinci Dereceden Denklemler"
                        },
                        new
                        {
                            Id = new Guid("10000003-0003-0003-0003-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2016),
                            EntityId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000002-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2016),
                            Value = "Matematik"
                        },
                        new
                        {
                            Id = new Guid("10000003-0003-0003-0003-000000000002"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2019),
                            EntityId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000003-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2019),
                            Value = "Geometri"
                        },
                        new
                        {
                            Id = new Guid("10000003-0003-0003-0003-000000000003"),
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2023),
                            EntityId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            EntityType = "Question",
                            ParameterDefinitionId = new Guid("00000004-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(2023),
                            Value = "Alan Hesaplama"
                        });
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer")
                        .HasColumnName("exam_type");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int>("OptionsLayout")
                        .HasColumnType("integer")
                        .HasColumnName("options_layout");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_questions_created_by");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            AttemptCount = 0,
                            CorrectCount = 0,
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1894),
                            CreatedBy = new Guid("cdce62f1-cdf8-4ca7-9e56-a5f85303cee6"),
                            Difficulty = 0,
                            ExamType = 0,
                            IsPublic = true,
                            OptionsLayout = 0,
                            Points = 2,
                            Status = 1,
                            Text = "5 + 3 x 2 işleminin sonucu kaçtır?",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1894),
                            ViewCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            AttemptCount = 0,
                            CorrectCount = 0,
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1898),
                            CreatedBy = new Guid("cdce62f1-cdf8-4ca7-9e56-a5f85303cee6"),
                            Difficulty = 1,
                            ExamType = 0,
                            IsPublic = true,
                            OptionsLayout = 0,
                            Points = 3,
                            Status = 1,
                            Text = "x² - 4 = 0 denkleminin çözüm kümesi nedir?",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1899),
                            ViewCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            AttemptCount = 0,
                            CorrectCount = 0,
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1902),
                            CreatedBy = new Guid("cdce62f1-cdf8-4ca7-9e56-a5f85303cee6"),
                            Difficulty = 0,
                            ExamType = 0,
                            IsPublic = true,
                            OptionsLayout = 0,
                            Points = 2,
                            Status = 1,
                            Text = "Bir dikdörtgenin alanı 24 cm², kısa kenarı 4 cm ise uzun kenarı kaç cm'dir?",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1902),
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_key");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_question_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_options_question_id");

                    b.ToTable("question_options", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0001-0001-0001-000000000001"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            Text = "16"
                        },
                        new
                        {
                            Id = new Guid("00000001-0001-0001-0001-000000000002"),
                            IsCorrect = true,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            Text = "11"
                        },
                        new
                        {
                            Id = new Guid("00000001-0001-0001-0001-000000000003"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            Text = "13"
                        },
                        new
                        {
                            Id = new Guid("00000001-0001-0001-0001-000000000004"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            Text = "10"
                        },
                        new
                        {
                            Id = new Guid("00000001-0001-0001-0001-000000000005"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            Text = "8"
                        },
                        new
                        {
                            Id = new Guid("00000001-0002-0002-0002-000000000001"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            Text = "{2}"
                        },
                        new
                        {
                            Id = new Guid("00000001-0002-0002-0002-000000000002"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            Text = "{-2}"
                        },
                        new
                        {
                            Id = new Guid("00000001-0002-0002-0002-000000000003"),
                            IsCorrect = true,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            Text = "{-2, 2}"
                        },
                        new
                        {
                            Id = new Guid("00000001-0002-0002-0002-000000000004"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            Text = "{4}"
                        },
                        new
                        {
                            Id = new Guid("00000001-0002-0002-0002-000000000005"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            Text = "Çözüm yok"
                        },
                        new
                        {
                            Id = new Guid("00000001-0003-0003-0003-000000000001"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            Text = "4 cm"
                        },
                        new
                        {
                            Id = new Guid("00000001-0003-0003-0003-000000000002"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            Text = "5 cm"
                        },
                        new
                        {
                            Id = new Guid("00000001-0003-0003-0003-000000000003"),
                            IsCorrect = true,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            Text = "6 cm"
                        },
                        new
                        {
                            Id = new Guid("00000001-0003-0003-0003-000000000004"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            Text = "8 cm"
                        },
                        new
                        {
                            Id = new Guid("00000001-0003-0003-0003-000000000005"),
                            IsCorrect = false,
                            OptionKey = "",
                            QuestionId = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            Text = "10 cm"
                        });
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_user_id");

                    b.Property<bool>("IsPasswordProtected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_password_protected");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("min_players");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_code");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("ix_rooms_host_user_id");

                    b.HasIndex("RoomCode")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_room_code");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.RoomPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("Team")
                        .HasColumnType("integer")
                        .HasColumnName("team");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_room_players");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_players_room_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_room_players_user_id");

                    b.ToTable("room_players", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdce62f1-cdf8-4ca7-9e56-a5f85303cee6"),
                            Avatar = "👤",
                            CreatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1622),
                            DisplayName = "muhammed",
                            Email = "muhammedturan@yahoo.com",
                            PasswordHash = "$2a$11$MKiZ20zeoqBTNPV5HxwRruNo8uK4KQmNcD9eK3ndrZQZCHyOoesAW",
                            UpdatedAt = new DateTime(2025, 11, 28, 4, 53, 35, 232, DateTimeKind.Utc).AddTicks(1623),
                            Username = "muhammedturan"
                        });
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_achievements");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("ix_user_achievements_achievement_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_achievements_user_id");

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_attempt_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("SelectedOptionKey")
                        .HasColumnType("text")
                        .HasColumnName("selected_option_key");

                    b.HasKey("Id")
                        .HasName("pk_user_answer");

                    b.HasIndex("ExamAttemptId")
                        .HasDatabaseName("ix_user_answer_exam_attempt_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_user_answer_question_id");

                    b.ToTable("user_answer", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.UserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AccuracyRate")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_rate");

                    b.Property<int>("BestWinStreak")
                        .HasColumnType("integer")
                        .HasColumnName("best_win_streak");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentWinStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_win_streak");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer")
                        .HasColumnName("current_xp");

                    b.Property<int>("FastestAnswerTime")
                        .HasColumnType("integer")
                        .HasColumnName("fastest_answer_time");

                    b.Property<int>("GlobalRank")
                        .HasColumnType("integer")
                        .HasColumnName("global_rank");

                    b.Property<int>("HighestScore")
                        .HasColumnType("integer")
                        .HasColumnName("highest_score");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("MonthlyRank")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_rank");

                    b.Property<int>("TotalCorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("total_correct_answers");

                    b.Property<int>("TotalGamesLost")
                        .HasColumnType("integer")
                        .HasColumnName("total_games_lost");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("total_games_played");

                    b.Property<int>("TotalGamesWon")
                        .HasColumnType("integer")
                        .HasColumnName("total_games_won");

                    b.Property<int>("TotalQuestionsAnswered")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions_answered");

                    b.Property<int>("TotalWrongAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("total_wrong_answers");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WeeklyRank")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_rank");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision")
                        .HasColumnName("win_rate");

                    b.Property<int>("XpToNextLevel")
                        .HasColumnType("integer")
                        .HasColumnName("xp_to_next_level");

                    b.HasKey("Id")
                        .HasName("pk_user_stats");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_stats_user_id");

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Exam", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.Category", "Category")
                        .WithMany("Exams")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_category_category_id");

                    b.HasOne("Tiroksin.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_users_creator_id");

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ExamAttempt", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_attempt_exam_exam_id");

                    b.HasOne("Tiroksin.Domain.Entities.User", "User")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_attempt_users_user_id");

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_question_exam_exam_id");

                    b.HasOne("Tiroksin.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_question_questions_question_id");

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.GameAnswer", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Answers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_answers_game_sessions_game_session_id");

                    b.HasOne("Tiroksin.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_answers_questions_question_id");

                    b.HasOne("Tiroksin.Domain.Entities.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .HasConstraintName("fk_game_answers_question_options_selected_option_id");

                    b.HasOne("Tiroksin.Domain.Entities.User", "User")
                        .WithMany("GameAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_answers_users_user_id");

                    b.Navigation("GameSession");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.Room", "Room")
                        .WithMany("GameSessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_sessions_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.GameSessionPlayer", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_players_game_sessions_game_session_id");

                    b.HasOne("Tiroksin.Domain.Entities.User", "User")
                        .WithMany("GameSessionPlayers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_players_users_user_id");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ParameterValue", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.ParameterDefinition", "ParameterDefinition")
                        .WithMany("Values")
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parameter_values_parameter_definitions_parameter_definition");

                    b.Navigation("ParameterDefinition");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Question", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_users_created_by");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Room", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.User", "Host")
                        .WithMany("HostedRooms")
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_users_host_user_id");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.RoomPlayer", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_players_rooms_room_id");

                    b.HasOne("Tiroksin.Domain.Entities.User", "User")
                        .WithMany("RoomPlayers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_players_users_user_id");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_achievements_achievement_id");

                    b.HasOne("Tiroksin.Domain.Entities.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_users_user_id");

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.UserAnswer", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("UserAnswers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answer_exam_attempt_exam_attempt_id");

                    b.HasOne("Tiroksin.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answer_questions_question_id");

                    b.Navigation("ExamAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.UserStats", b =>
                {
                    b.HasOne("Tiroksin.Domain.Entities.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("Tiroksin.Domain.Entities.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_stats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Category", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Exam", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ExamAttempt", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.ParameterDefinition", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.Room", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Tiroksin.Domain.Entities.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("ExamAttempts");

                    b.Navigation("GameAnswers");

                    b.Navigation("GameSessionPlayers");

                    b.Navigation("HostedRooms");

                    b.Navigation("RoomPlayers");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
